export const GET_ALL_GAMES_REQUEST = "GET_ALL_GAMES_REQUEST";
export const GET_ALL_GAMES_SUCCESS = "GET_ALL_GAMES_SUCCESS";
export const GET_ALL_GAMES_FAILED = "GET_ALL_GAMES_FAILED";

export const SET_FAVORITE = "SET_FAVORITE";
export const UNSET_FAVORITE = "UNSET_FAVORITE";

export const SHOW_FULL_GAME_INFO = "SHOW_FULL_GAME_INFO";
export const CLOSE_FULL_GAME_INFO = "CLOSE_FULL_GAME_INFO";
